### ISSUE TITLE
Compatibility with Bash on Ubuntu on Windows ?

### ISSUE THREAD

**Issue by yvan-sraka** [railsware/black-screen#1005]
Hello,

I recently installed [Bash on Ubuntu on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/about), and I'm really sad: because the terminal provided by Windows is the classic old `CMD.exe`, so I wonder about how it would be possible to use this Bash under WSL (Windows Subsystem for Linux) inside Black Screen?

Thank you very much,

**Comment by the4ndy** [comment]
not really relevant to this project, but just so you know, the BASH command for "Bash for Win 10" is in the PATH by default, if you open cmd.exe and type bash and hit enter you are dropped to a bash prompt.

**Comment by vshatskyi** [comment]
Closing in favour of https://github.com/railsware/black-screen/issues/800
