### ISSUE TITLE
High response time

### ISSUE THREAD

**Issue by gocreating** [railsware/black-screen#1018]
Environment:
- MacBook Air
- OS X El Capitan
- 4G RAM
- 128G Storage

I have to wait several seconds when every type of single letter. The response time is pretty high.

Is this typical?

**Comment by drew-gross** [comment]
Unfortunately yes. There are a lot of performance problems we need to work out before releasing version 1.0.

**Comment by gocreating** [comment]
@drew-gross Thanks for your answer!

**Comment by kevingimbel** [comment]
Can confirm. I am seeing similar performance issues. Typing lacks behind quite noticeably.

My specs: 
- MacBook Pro
- macOS Sierra (10.12.1)
- 8GB Ram
- 2,7GHz Intel Core i5

---

By the way, you've been featured on DigitalOcean's "Infastructure as a Newsletter" Newsletter, way to go! :)

**Comment by vshatskyi** [comment]
Should be significantly faster as of https://github.com/vshatskyi/black-screen/commit/93d5c3d10e67d00cafad053b5a920a6adee9eefd

**Comment by kevingimbel** [comment]
@vshatskyi how can I update? I tried with ` brew cask reinstall black-screen` but that gives me the same version as before (0.2.142).

**Comment by vshatskyi** [comment]
You can download the release from this page, @kevingimbel: https://github.com/vshatskyi/black-screen/releases

**Comment by kevingimbel** [comment]
@vshatskyi thanks! Didn't think about checking the releases. 

I just installed the update and it feels 100x faster - no lack on input anymore! Now I'm able to give Black Screen a serious try. :)
