### ISSUE TITLE
It's kinda slow...

### ISSUE THREAD

**Issue by milesalex** [railsware/black-screen#1030]
Any reason why?

**Comment by vshatskyi** [comment]
@milesalex did you try to install the latest release? https://github.com/railsware/black-screen/releases

**Comment by milesalex** [comment]
This fixed the issue. Can you add automatic updating to the build?

**Comment by vshatskyi** [comment]
Will do, @milesalex! I marked it as a high priority issue. https://github.com/railsware/black-screen/issues/443
