### ISSUE TITLE
Set up donations

### ISSUE THREAD

**Issue by vshatskyi** [railsware/black-screen#86]
https://github.com/blog/57-getting-paid-the-open-source-way

**Comment by mzgnr** [comment]
how about crowd funding ?

**Comment by G07cha** [comment]
This issue may be resolved as we create first stable version I think.

**Comment by flawiddsouza** [comment]
@mzgnr I think its way too early for crowd funding.

**Comment by joshtoo** [comment]
Agree with @G07cha here - IMO adding solid support that covers what people user terminals for everyday ( vim, nano, scp, ssh, grep, tail and so on ) and stabilize that across, *Nix, OSX & Windoz then couple that with the features that black-screen brings to the table ( auto-complete ftw ) then tag a stable v1.0.0. Going after crowd funding / donations to cover the costs of the increase in both human and infrastructure resources needed to tackle some of the larger "Nice to have" features would be both warranted and viable.

**Comment by nblackburn** [comment]
You could make it donationware like Cyberduck and HeidiSQL where donating gives you a license key to remove the donation buttons from the application. I think this model is great and would love to see more applications going this way.
